[package]
name = "handwritingrecognition"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
fern = "0.7.0"
itertools = "0.13.0"
log = "0.4.22"
mnist = "0.6.0"
ndarray = "0.16.1"
statrs = "0.17.1"

